newsite/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('visit.urls')),
]

visit/urls.py
from django.urls import path
from .views import home, detail, add_user, delete_user

app_name = 'visit'

urlpatterns = [
    path('', home, name="home"),
    path('<int:user_id>/', detail, name="detail"),
    path('add_user/', add_user, name="add_user"),
    path('delete_user/<int:user_id>/', delete_user, name="delete_user"),
]

visit/models.py
from django.db import models


class Visit(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()

    def __str__(self):
        return self.name

visit/forms.py
from django.forms import ModelForm
from .models import Visit


class UserForm(ModelForm):
    class Meta:
        model = Visit
        fields = ['name', 'email']

visit/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Visit
from .forms import UserForm
from django.http import HttpResponse


def home(request):
    users = Visit.objects.all()  # list of objects
    context = {
        "users": users
    }
    return render(request, 'index.html', context)


def detail(request, user_id):
    user = get_object_or_404(Visit, pk=user_id)
    if request.method == 'GET':
        form = UserForm(instance=user)
        return render(request, 'detail.html', {'form': form, 'user': user})
    else:
        try:
            form = UserForm(request.POST, instance=user)
            form.save()
            return redirect('/')
        except ValueError:
            return render(request, 'add_user.html', {'form': form, 'user': user, 'error': 'Bad data passed in. Try again'})


def add_user(request):
    if request.method == 'GET':
        return render(request, 'add_user.html', {'form': UserForm()})
    else:
        try:
            form = UserForm(request.POST)
            newuser = form.save()
            return redirect('/')
        except ValueError:
            return render(request, 'add_user.html', {'form': UserForm(), 'error': 'Bad data passed in. Try again'})


def delete_user(request, user_id):
    user = get_object_or_404(Visit, pk=user_id)
    if request.method == 'POST':
        user.delete()
        return redirect('/')
    else:
        user.delete()
        atbilde = "Deleted " + user.name
        return HttpResponse(atbilde)

visit/templates/add_user.html
{% extends 'base.html' %}
{% block content %}
<h2>Please add new  user:</h2><hr>
<h2>{{ error }}</h2>
<form method="POST">
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit">Add User</button>
</form>

{% endblock %} 

visit/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
	      integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
	<title>Visit page</title>
</head>
<body>
	<div class="container">
		{% include 'navbar.html' %}
		{% block content %}
		replace me
		{% endblock %}
	</div>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
	        integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
	        crossorigin="anonymous"></script>

</body>
</html>

visit/templates/detail.html
{% extends 'base.html' %}

{% block content %}

{{ error }}
<h1> Change or delete user info</h1>
<br>

	<form method="POST">
		{% csrf_token %}
		{{ form.as_p }}
		<div class="btn-group">
		<button type="submit">Save</button>
	</form>


	<form method="POST" action="{% url 'visit:delete_user' user.id %}">
		{% csrf_token %}
		<button type="submit">Delete</button>

	</form>

</div>

{% endblock %} 

visit/templates/index.html
{% extends 'base.html' %}

{% block content %}
<h2>User database contains {{ users.count }} user{{ users.count|pluralize }}</h2>
<br>
<ul>
	{% for user in users %}
	<li>ID: {{ user.id }}<br>
		Username:  <a href="{% url 'visit:detail' user.id %}">{{user.name}}</a><br>
		E-mail: {{user.email}}
	</li><br>
	{% endfor %}
</ul>
{% endblock %} 

visit/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'visit:home' %}">List all users <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'visit:add_user' %}">Add user</a>
      </li>

    </ul>
  </div>
</nav>